### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by QiangShiPKU** [TencentAILabHealthcare/pysodb#1]
```
conda create --name pysodb python=3.8 -y
conda activate pysodb

git clone https://github.com/TencentAILabHealthcare/pysodb.git

cd pysodb
python setup.py install
```

The last installation command reports an error:
`error: urllib3 2.0.0a3 is installed but urllib3<1.27,>=1.21.1 is required by {'requests'}`

After installing `pip install urllib3==1.26.14` and pysod, other errors emerge when `import pysodb`

**Comment by WinterPan2017** [comment]
Thanks for your attention. We have fixed this issue. Please install pysodb referring to the latest instruction. Feel free to re-open it if you have any further questions.
